# Background and foreground colors
background = #181c1f
foreground = #e1e4e8

# Standard colors
palette = 0=#181c1f
palette = 1=#ea4a5a
palette = 2=#79b8ff
palette = 3=#ffdf5d
palette = 4=#ffdf5d
palette = 5=#f9826c
palette = 6=#79b8ff
palette = 7=#e1e4e8

# Bright colors
palette = 8=#6a737d
palette = 9=#ea4a5a
palette = 10=#79b8ff
palette = 11=#ffdf5d
palette = 12=#79b8ff
palette = 13=#f9826c
palette = 14=#79b8ff
palette = 15=#e1e4e8
