# hyprland configuration file

general {
    gaps_out = 2
    gaps_in = 2
    border_size = 2
    no_border_on_floating = false
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(676e95aa)
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }

}

animations {
    enabled = true
    workspace_wraparound = false
}

# Disable window transparency
#windowrulev2 = opacity 1.0 override,class:.*
